version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf/conf.d:/etc/nginx/conf.d
      - /etc/nginx/conf/cacert.pem:/etc/nginx/cacert.pem
      - /etc/nginx/conf/private.key:/etc/nginx/private.key
      - /var/log:/var/log/nginx
      - /home/dist/out:/usr/share/nginx/html