# 定义一个名字
name: deploy-website
# 指定在main分支push时执行
on:
  push:
    branches: [main]
# 指定任务
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest # 指定操作系统

    # 步骤
    steps:
      # uses指定用什么包
      # name指定名称
      # run指定操作
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: install nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20.x"

      - name: instal deps
        run: npm install # 安装依赖

      - name: build app
        run: npm run build # 构建应用

      - name: copy dist file with scp
        uses: easingthemes/ssh-deploy@main
        # 这个文件会公开
        env:
          host: ${{ secrets.REMOTE_HOST }} # 指定 SSH 主机
          username: ${{ secrets.REMOTE_USER }} # 指定 SSH 用户名
          password: ${{ secrets.REMOTE_PASS}} # 指定 SSH 密码
          port: 22 # 指定 SSH 端口为 22
          SOURCE: './out' # 源目录，也就是构建后的目录
          TARGET: '/home/dist' # 指定远程服务器上的目标目录，需要提前创建
